Public Class MensajesSistema
    Public Shared ReadOnly mensajesGenerales As New Dictionary(Of String, String) From {
        {"YA_FUE_ANULADO_CANCELADO", "ESTE REGISTRO YA FUE ANULADO/CANCELADO"},
        {"SELECCIONE_REGISTRO", "POR FAVOR, SELECCIONE UN REGISTRO"},
        {"SELECCION_FILA_CONTENEDOR", "DEBE SELECCIONAR UNA FILA DEL REGISTRO CONTENEDOR"},
        {"SELECCION_FILAS_CONTENIDAS", "SELECCIONE REGISTROS CONTENIDOS POR EL REGISTRO"},
        {"GUARDADO_EXITOSO", "SE GUARDÓ EXITOSAMENTE"},
        {"ACTUALIZACION_EXITOSA", "ACTUALIZACIÓN REALIZADA EXITOSAMENTE"},
        {"CONFIRMACION_ELIMINAR", "¿ESTÁ SEGURO QUE DESEA ELIMINAR ESTE REGISTRO?"},
        {"DATOS_INVALIDOS", "LOS DATOS INGRESADOS NO SON VÁLIDOS"},
        {"ARCHIVO_GUARDADO", "EL ARCHIVO SE GUARDÓ CORRECTAMENTE"},
        {"CONFIRMACION_ACTUALIZAR", "¿ESTÁ SEGURO QUE DESEA ACTUALIZAR ESTE REGISTRO?"},
        {"REGISTRO_EXISTENTE", "EL REGISTRO YA EXISTE"},
        {"OPERACION_NO_PERMITIDA", "ESTA OPERACIÓN NO ESTÁ PERMITIDA"},
        {"SIN_RESULTADOS", "NO SE ENCONTRARON RESULTADOS"},
        {"CON_ARCHIVO_EVIDENCIA", "EL REGISTRO YA CONTIENE ARCHIVOS DE EVIDENCIA"},
        {"SIN_ARCHIVO_EVIDENCIA", "EL REGISTRO NO CONTIENE ARCHIVOS DE EVIDENCIA"},
        {"RACION_PREPARADA", "LA RACIÓN YA FUE PREPARADA"},
        {"EXISTEN_OBSERVACIONES", "EXISTEN OBERVACIONES, NO PUEDE CONTINUAR CON EL PROCESO"},
        {"FECHA_INICIO_MAYOR_FIN", "LA FECHA DE INICIO NO PUEDE SER MAYOR QUE LA FECHA DE FIN"},
        {"SELECCIONE_REGISTRO_HIJO_MOLINO", "DESPLIEGUE DETALLE Y SELECCIONE CON DOBLE CLIC LOS REGISTROS DE ALIMENTO A PREPARAR"},
        {"SELECCIONE_MISMO_TIPO_ALIMENTO", "SELECCIONE RACIÓN DEL MISMO TIPO DE ALIMENTO"},
        {"STOCK_INSUFICIENTE", "EL STOCK ES INSUFICIENTE PARA REALIZAR ESTA OPERACIÓN"}
    }
End Class
